= rust_hls
:last-update-label!:
:toc: macro

Real high-level synthesis from Rust using Bambu

For now the Readme is more of a notepad of things I want to keep track of than an actual readme. I will try to clean it up later.

You should probably not use this crate yet.

== Usage

My first attempt at rust_hls involved a proc macro that would get expanded to a rust-hdl component which wraps the generated Verilog using verilator. This was a bad idea, because the performance is horrible and everything runs at compile time. I tried to mitigate that by adding multiple levels of caching, but it was still too slow too be usable. Next I tried using a rust buildscript, but that is still to slow, because it gets called by multiple tools. It is also a compatibility nightmare as bambu and verilator have to be available during builds. That makes rust_hls not very portable. I think the best approach is to move all the HLS and verilation to a separate program that places the generated files into the project.  They should then be commited to the repository so users of the hls module do not need to run the toolchain. This way the only extra compiletime dependency is a C compiler to compile the verilated files.



== Making it convenient to use HLS from rust

In the previous post we synthesized a Verilog counter from Rust code. Then we manually pasted that Verilog into a handmade `rust-hdl` component, so that we can use it. This is not very convient. 

In an ideal world one would be able to annotate a function with something like `#[hls]` and then a rust macro would do all the conversions for you. In this post we will explore how to do that.

.The toolchain
[pikchr]
....
   arrow right 150% ".rs file with macros" "Source"
   box rad 10px "Transform to LLVM" "(rustc)" fit
   arrow right 190% "LLVM IR file" "Intermediate"
   box rad 10px "HLS to verilog" "(bambu)" fit
   arrow right 130% "Verilog module" "Intermediate"
   box rad 10px "Embed into rust-hdl" "(yosys)" fit
   arrow right 200% "rust-hdl module" "Target"
....

So we need to write three rust macros. One that converts a file to LLVM IR, one that converts LLVM IR to Verilog, and one that embeds the Verilog into a rust-hdl component.

The first two macros will be quite hacky, as we will need to invoke external tools from rust. The third macro should be quite straightforward, as it only needs to wrap the Verilog in a rust-hdl component. We will start with the third macro, as it is the easiest.

== Converting a rust file with some kind of Verilog to a rust-hdl component

After the other two macros created Verilog and placed it into the file we now need to wrap that up for `rust-hdl`. First I will try to define some goals I want to achieve.

.Goals
- It should be able to convert the Verilog counter example to a rust-hdl component.
- It should be able to convert a Verilog module synthesized by bambu to a rust-hdl component.
- It should be callable as a rust macro.
- It should take a Verilog string as input.

Lets try to split the task of create that rust macro that converts a verilog to rusthdl into smaller subtasks.

.Task subdivision
[%collapsible]
====
.1
- Create a rust macro that converts a verilog to rusthdl

.2
- Create library that converts a verilog string to a rust-hdl string
- Create a macro around that library

.3
- Create a rust crate for the converter library
- Figure out the interface of the library functions
- Parse Verilog strings
- Create rust-hdl strings
- Create a macro around that library

.4
- Create a rust crate for the converter library
- Figure out the interface of the library functions
- Parse Verilog strings
- Extract the top module interface
- Create rust-hdl module
- Insert Verilog into rust-hdl module
- Create a macro around that library
====

.Tasks
- Create a rust crate for the converter library
- Parse Verilog strings
- Extract the top module interface
- Create rust-hdl module
- Insert Verilog into rust-hdl module
- Figure out the interface of the library functions
- Create a macro around that library

I will try to work the tasks in that order and log any problems here.

=== Create a rust crate for the converter library

Easy, I just run `cargo init --lib` and create a new crate. Why did I even add a task for this?

=== Parse Verilog strings

I tried the `verilog` parser crate, but it had problems parsing even basic Verilog. Next I tried the `sv-parser` crate. That one is actually build for SystemVerilog, but that is just a superset of Verilog, so it should work.